---
title: "Lab 1 (4793) AGP"
author: "Austin Parker"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Sample Mean Function, $\bar x$

```{r}
SampleMean = function(x = matrix(0:8,nrow = 3, ncol = 3, byrow = TRUE)){       # default matrix "x" for function
  # print(x)
  
    n = nrow(x)      # define the number of rows in matrix x
  
  # Sums the columnd and rows
    col.sum = apply(x, 2, sum) 
    # row.sum = apply(x, 1, sum)
  
        # Adds sums to original matrix (not necessary)
          # x <- cbind(x, Rsum = row.sum)
          # x <- rbind(x, Csum = c(col.sum, sum(col.sum)))
          # print(x)
  
  # Calculates the sample mean for each column  
    xbar = 1/n * col.sum
    print(xbar)
    print(x)
}

SampleMean()
```

# Sample Covariance Matrix, $s_{jk}$

```{r}
SampleCovariance = function(X = matrix(c(15,40,37,31,19,47,45,74,16), nrow = 3, ncol = 3, byrow = TRUE)) {      # create default matrix for function

    n=nrow(X)
    p=ncol(X)

    sums=apply(X, MARGIN = 2, FUN=sum) #sum of measurements for each variable
    xbar=(1/n)*sums

    s <- matrix(NA, nrow = p, ncol = p)  # create matrix with same dimensions as input matrix
    v <- vector(mode = "numeric", length = n)

    for (i in 1:p) {
      for (k in 1:p) {
        for (j in 1:n) {
          v[j] <- (X[j,i] - xbar[i]) * (X[j,k] - xbar[k])
        }
    
        s[i,k] <- 1/(n-1) * sum(v)
      }
  
    
    }
    print(s)
}


SampleCovariance()


cov(X)
```

# Dr. Stewart's way of Sample Correlation

```{r, eval = FALSE}
S.kk = function(X <- matrix(1:4, nrow = 2, ncol = 2)){      # create default matrix for function
  
  # calculates the number of rows "n" and number of columns "p"
    n = nrows(X)
    p = ncols(X)
    
  # calculates the sample means for the columns and stores in a vector
    # sum = apply(X, 2, FUN = sum)
    
    vbar = sum(X[,v])/n
    ubar = sum(X[,u])/n
  
  # calculate s_ik
    for (j in 1:n) {
      s.ik = 
    }
}
```

```{r, eval = FALSE}
X <- matrix(c(15,40,37,31,19,47,45,74,16), nrow = 3, ncol = 3, byrow = TRUE)      # create default matrix for function
  # X
  
  # calculates the number of rows "n" and number of columns "p"
    n = nrow(X)
    p = ncol(X)
    
  # calculates the sample means for the columns and stores in a vector
    # sum = apply(X, 2, FUN = sum)
    
    v=1
    u=1
    vbar = sum(X[,v])/n
    ubar = sum(X[,u])/n
  
    
  # calculate s_ik
    # create vector to store "j" iterations
        a <- vector("numeric", length = n)
        
    for (j in 1:n) {
      a[j] <- (X[j,v] - vbar) * (X[j,u] - ubar)
    }
    print(s.ik <- 1/(n-1) * sum(a))
    
  # calucate s covariance matrix
    # create covariance matrix
      s <- matrix(NA, nrow = p, ncol = p)
    
    for (i in 1:p) {
      for (k in 1:p) {
        s[i,k] <- s.ik
      }
    }
    
cov(X)

```

```{r, eval = FALSE}
X <- matrix(c(15,40,37,31,19,47,45,74,16), nrow = 3, ncol = 3, byrow = TRUE)      # create default matrix for function
  # X
  
  # calculates the number of rows "n" and number of columns "p"
    n = nrow(X)
    p = ncol(X)
    
  # calculates the sample means for the columns and stores in a vector
    # sum = apply(X, 2, FUN = sum)
    
    i=1
    k=1
    ibar <- vector()
    kbar = sum(X[,k])/n
  
    # calucate s covariance matrix
      # create covariance matrix
        s <- matrix(NA, nrow = p, ncol = p)
      
      # create vector to store "j" iterations
        a <- vector("numeric", length = n)
    
    for (i in 1:p) {
      for (k in 1:p) {
        for (j in 1:n) {
          # a[j] <- (X[j,i] - ibar) * (X[j,k] - kbar)
          # print(a)
          print(ibar)
        }
        # print(s.ik <- 1/(n-1) * sum(a))
      }
    }  
  
        
    
    

    
cov(X)

```


# Sample Correlation Matrix, 

```{r}
SampleCorrelation = function(X = matrix(c(15,40,37,31,19,47,45,74,16), nrow = 3, ncol = 3, byrow = TRUE)) {      # create default matrix for function


    n=nrow(X)
    p=ncol(X)

    sums=apply(X, MARGIN = 2, FUN=sum) #sum of measurements for each variable
    xbar=(1/n)*sums

    s <- matrix(NA, nrow = p, ncol = p)  # create matrix with same dimensions as input matrix
    r <- matrix(NA, nrow = p, ncol = p)  # create matrix with same dimensions as input matrix
    v <- vector(mode = "numeric", length = n)

    for (i in 1:p) {
      for (k in 1:p) {
        for (j in 1:n) {
          v[j] <- (X[j,i] - xbar[i]) * (X[j,k] - xbar[k])
        }
        
        s[i,k] <- 1/(n-1) * sum(v)
      }
    }
    
    for (i in 1:p) {
      for (k in 1:p) {
        r[i,k] <- s[i,k] / (sqrt(s[i,i]) * sqrt(s[k,k]))
        # the code below helps diagnose the problem of inserting the line above from filling in the matrix "r" (k,k) k=2 is need for r_{1,2}, but won't be defined for another 3 loops
          # print(c(i,k))
          # print(r)
      }
    }
    print(r)
}

SampleCorrelation()

cor(X)
```


